version: 0.0
os: linux

files:
  - source: /target/my-java-app.jar
    destination: /home/ubuntu/my-java-app/

hooks:
  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 180
      runas: ubuntu
