version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - apt-get update
      - apt-get install -y maven
      - mvn -v

  pre_build:
    commands:
      - echo Cleaning project...
      - mvn clean

  build:
    commands:
      - echo Building the JAR...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Build completed. Preparing artifact...
      - mkdir -p build-output
      - cp target/*.jar build-output/spring.jar
      - cp appspec.yml build-output/
      - cp -r scripts build-output/

artifacts:
  files:
    - build-output/**/*
  base-directory: build-output
  discard-paths: yes
