version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - apt-get update
      - apt-get install -y maven
      - mvn -v

  pre_build:
    commands:
      - echo Cleaning project...
      - mvn clean

  build:
    commands:
      - echo Renaming output JAR to spring.jar...
      - echo Building the JAR...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Build completed.
      - mkdir -p build-output
      - cp target/*.jar spring.jar build-output/
      - cp appspec.yml build-output/
      - cp -r scripts build-output/

artifacts:
  files:
    - build-output/**/*
  discard-paths: yes
